# -*- coding: utf-8 -*-
"""Copy of [READ-ONLY]DS4SE26Week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjKSBGgMDvR_ZFlFhKR4XM8mjcY6heXo

# 0. Install and import the required dependencies

**You may add or remove based on your assigned model!**
"""

#!pip install -U tokenizers transformers accelerate bitsandbytes

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from google.colab import userdata

"""# 1. Authentication & Model selection

**Retrieve the Hugging Face token securely from Colab's "Secrets" tab (the key icon on the left).**
"""

try:
    hf_token = userdata.get('HF_TOKEN')
except userdata.SecretNotFoundError:
    print("WARNING: 'HF_TOKEN' not found in Colab Secrets.")
    hf_token = None

"""**CHANGE THIS TO YOUR ASSIGNED MODEL**"""

# A smaller model that fits on a free Colab GPU
model_name = "ibm-granite/granite-3.3-8b-instruct"

"""# 2. Hardware optimization (Quantization)"""

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True, # What is loaded in 4 bit? why?
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

"""# 3. Load the tokenizer & model"""

print(f"Loading Tokenizer for {model_name}...")
tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    token=hf_token,
    trust_remote_code=True # Does your model need it?
)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left" # What about right?

print("Loading Model on Colab T4 GPU...")
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    token=hf_token,
    trust_remote_code=True, # Does your model need it?
    quantization_config=bnb_config, # from section 2 above
    torch_dtype=torch.float16
)

"""# 4. INFERENCE & HYPERPARAMETER TUNING

**Design the prompt (Does this design/technique have a name?)**
"""

prompt = [
    {
        "role": "system",
        "content": "You are a helpful software assistant. Your job is to explain the functionality of the provided code in simple terms."
    },
    {
        "role": "user",
        "content": """Please analyze the following source code:

        <source_code>
        public class Task {

            public static void main(String[] args) {
                String id1   = "AMQ-2104";
                double files = 8.0;
                String id2   = "AMQ-317";
                double dmm   = 0.45;

                int n = Integer.parseInt(id1.split("-")[1])
                      + Integer.parseInt(id2.split("-")[1]);

                int digits = 0;
                while (n > 0) {
                    n = n / 10;
                    digits++;
                }

                int impact = (int) (files * dmm);

                System.out.println("Combined digits: " + digits);
                System.out.println("Impact: " + impact);
            }
        }
        </source_code>"""
    }
]

"""**Convert the prompt into tokens**"""

inputs = tokenizer.apply_chat_template(
    prompt,
    add_generation_prompt=True,
    return_dict=True,
    return_tensors="pt"
).to(model.device)

"""**Understand these hyperparameters and then tune them for better inference**"""

print("Generating response...\n")
outputs = model.generate(
    **inputs,
    max_new_tokens=512, # which tokens?
    temperature=0.5, # ?
    top_p=0.8, # ?
    do_sample=True, # What if this toggle is false?
    pad_token_id=tokenizer.eos_token_id
)

"""**Convert the output back from tokens into human-readable text and display it**"""

input_length = inputs['input_ids'].shape[1]
response = tokenizer.decode(outputs[0][input_length:], skip_special_tokens=True)

print("Model output:")
print(response)